### ISSUE TITLE
store data in RDF

### ISSUE THREAD

**Issue by jibe-b** [allofphysicsgraph/proofofconcept#14]
Hi @bhpayne,

I just discovered your work and am really interested. I have been thinking about doing something of the same kind but without going as far as you have been. I consider tinkering a bit on what you have done to see if your approach and mine are compatible.

Here is what I have in mind, first.

I know a bit about [RDF](http://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0CC0QFjAC&url=http%3A%2F%2Fwww.w3.org%2FRDF%2F&ei=hCDeVKD7MtPSaI-HgsgB&usg=AFQjCNF4CBpXIq0V-mnqIeG4rbwyG37LPQ) and I would rather store data in a RDF graph than in q non-RDF XML file.

If data was stored in a RDF file, it would be possible to extract it using [RDFlib](http://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CCEQFjAA&url=http%3A%2F%2Fwww.rdflib.net%2F&ei=5iDeVMC6NszdauzTgKAM&usg=AFQjCNHQLMoTK1tIO4-8auiBnQVhD9_LBQ) easily and use your code to compute (only adding a layer, so that the non-RDF XML files can be created). 

But it would also be possible to work from the terminology side, first by writing an [ontology](http://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CCsQFjAB&url=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FWeb_Ontology_Language&ei=ViHeVNaXCMHxatPqgoAK&usg=AFQjCNHkl4g-Z5E7x-YJc1Av3QEpYLKj_Q) for the concepts (OWL classes) used in the graph and then to compute on the data, taking advantage of the RDF-possiblities.

What do you think about it? These are just fresh thoughts, but they are the result of the reflexions I have had plus what I understood of your project.

If you want to have an idea of what I am specialising in (as a personal projet alongside my studies), take a look at [http://jibe-b.github.io](http://jibe-b.github.io) (but don't expect too much, for example I have not yet written anything about derivations graphs and what I mostly use these pages as a notebook).

Best,

jibe

**Comment by jibe-b** [comment]
Ok, I read the user manual.

The XML vocabulary you have defined can be traslated into an ontology easily. Then it will be possible to add axioms on the classes (concepts) to unable further computation on general knowlege (reasoner, etc).

PS: Sorry, it's to much a mess on http://jibe-b.github.io I wil tell you when I make it readible.

**Comment by jibe-b** [comment]
I don't know if you are used to working on OWL ontologies, but here is one I just started (and not populated yet). Feel free to explore translating your XML vocabulary into an OWL ontology.

http://opendata1.opendata.u-psud.fr:8080/webprotege/#Edit:projectId=fc11d1c6-e755-4e62-be3d-70e8774d704d

**Comment by jibe-b** [comment]
and [here](http://vowl.visualdataweb.org/webvowl/index.html#iri=http://jibe-b.github.io/ontology/physics-derivations-test), a visualisation of the onotlogy. I have not implemented a lot. If you add classes or properties on webpretege, the visualisation won't update. You have to store it somewhere on the web (this link displays a snapshot of the ontology, store on my blog) and use VOWL to display this custom ontology.

**Comment by msgoff** [comment]
Hello Jibe,


 Thank you for your interest in the project. Ben in out of town until the 22nd. I am sure that he will contact your shortly upon his return. He will be very interested in working with you on this.

Have a Great Week!

Mike

**Comment by bhpayne** [comment]
Hello Jibe-b,

You have a great project going and I'm excited about your work. I'd like to discuss collaboration; either email or phone works for me.

**Comment by allofphysics** [comment]
May I have your email address to contact you directly?

Thanks

Mike

**Comment by bhpayne** [comment]
Could you share the RDF file (or whatever backend data format you're using) to create the page
http://vowl.visualdataweb.org/webvowl/index.html#iri=http://jibe-b.github.io/ontology/physics-derivations-test

My email is in the Python source files, ie
https://github.com/allofphysicsgraph/proofofconcept/blob/master/bin/build_connection_set_pdf.py

**Comment by bhpayne** [comment]
I started a project to define Physics derivations
http://webprotege.stanford.edu/#Edit:projectId=c816e793-12eb-4bfd-a4c7-3db0ba44b34c

The project is populated with data from
https://github.com/allofphysicsgraph/proofofconcept/wiki/Inference-Rules
and
https://github.com/allofphysicsgraph/proofofconcept/wiki/Operators

**Comment by jibe-b** [comment]
Until April I won't have much time but I'll try to be active at least at some times.

VOWL displays the file that is at the end of the URI, i.e. http://jibe-b.github.io/ontology/physics-derivations-test

I took a look at the ontology you've started, and it's nice that you already have a tree. The ontology should not need a lot of axioms, yet it would be valuable to define the basical axiomisation, at least to manage to contribute together to the same ontology.

I see various important thing to take into account and I'll try to tell you them when I can but I unfortunately don't have time yet.

**Comment by bhpayne** [comment]
I wrote a converter for the database that creates RDF triples.

The output syntax isn't compliant exactly with https://www.w3schools.com/xml/xml_rdf.asp because I'm not clear what syntax is actually relevant for use with other RDF tools.

If the syntax is something like https://www.w3schools.com/xml/xml_rdf.asp the update should be easy
