### ISSUE TITLE
convert list of symbols in AST to Sympy expression

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/proofofconcept#189]
as per https://physicsderivationgraph.blogspot.com/2020/05/replacing-symbols-in-sympy-expression.html
need to manually convert list of symbols to Sympy

    >>> import sympy
    >>> from sympy.parsing.latex import parse_latex
    >>> sympy.srepr(parse_latex('x^2 - y^2 = (x+y)(x-y)'))
    "Equality(Add(Pow(Symbol('x'), Integer(2)), Mul(Integer(-1), Pow(Symbol('y'), Integer(2)))), Mul(Add(Symbol('x'), Mul(Integer(-1), Symbol('y'))), Add(Symbol('x'), Symbol('y'))))"

**Comment by bhpayne** [comment]
593020475c821682f0230d23bc8fa33b9663c63f

**Comment by bhpayne** [comment]
$ cat data.json | grep "\"AST\": " | grep "and pdg" | wc -l
     206
    $ cat data.json | grep "\"AST\": \"\"" | wc -l
     239
    $ cat data.json | grep "\"AST\":" | wc -l
     724

**Comment by bhpayne** [comment]
Used a script to convert 100 expression latex to Sympy

    import json
    import sympy
    from sympy.parsing.latex import parse_latex
    with open('data.json','r') as fil:
        dat = json.load(fil)

    for expr_global_id, expr_dict in dat['expressions'].items():
        #print(expr_dict['AST'])
        if expr_dict['AST']=="" and "langle" not in expr_dict['latex']:
            print('expr_global_id = ' + expr_global_id + "; latex is \n")
            print(expr_dict['latex'] + "\n")
            try:
                symp_expr = sympy.srepr(parse_latex(expr_dict['latex']))
            except Exception as err:
                print(err)
            print("suggested Sympy: \n\n" + symp_expr)
            go_to_next_expr = False
            while(not go_to_next_expr):
                user_in = input("\n[u]se this; [e]dit before using; [s]kip this expr_global_id:\n")
                if user_in=='s': # skip
                    go_to_next_expr=True
                elif user_in == 'u': # use
                    print('use this: ' + symp_expr)
                    # write symp_expr to dat
                    with open('data.json','r') as fil:
                        dat_ed = json.load(fil)
                    dat_ed['expressions'][expr_global_id]['AST'] = symp_expr
                    with open('data.json','w') as fil:
                        json.dump(dat_ed, fil, indent=4, separators=(",", ": "))
                    go_to_next_expr=True
                elif user_in == 'e': # edit
                    symp_expr = input("provide revision: \n")
                    print("here is what you wrote: \n" + symp_expr)
                else:
                    print("unrecognized option")

**Comment by iammosespaulr** [comment]
hey @bhpayne I've made a lot of improvements to the sympy latex parser over at my fork https://github.com/iammosespaulr/sympy/tree/mathpix . I haven't created a PR for it yet. It may benefit this project

**Comment by bhpayne** [comment]
Fully eliminated "and pdg" to SymPy

    $ cat data.json | grep "\"AST\": " | grep "and pdg" | wc -l
           0
    $ cat data.json | grep "\"AST\": \"\"" | wc -l
           0
    $ cat data.json | grep "\"AST\":" | wc -l
         897
