### ISSUE TITLE
math labels in graph not using d3js

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/proofofconcept#19]
alternative approaches for graphs with math labels

**Comment by bhpayne** [comment]
Mathematica supports labeled edges for directed graphs

http://reference.wolfram.com/language/ref/DirectedEdge.html

**Comment by msgoff** [comment]
Latex support and looks nice!
https://networkx.github.io/documentation/networkx-1.9/examples/drawing/labels_and_colors.html

**Comment by bhpayne** [comment]
Went with static images in d3js

http://allofphysicsgraph.github.io/proofofconcept/

**Comment by bhpayne** [comment]
See candidate software on https://examples.pyviz.org/search.html?q=graph
