### ISSUE TITLE
neato out of memory

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/proofofconcept#2]
neato failure to create cairo surface out of memory

ubuntu, fresh install

**Comment by msgoff** [comment]
0,1,9 create neato out of memory errors on my laptop.

**Comment by bhpayne** [comment]
no ability to reproduce this issue; not clear what the context was.

**Comment by bhpayne** [comment]
On DigitalOcean Ubuntu 18.04 in a Docker container,

    $ neato -Tpng graphviz.dot -o all_derivation.png 
    neato: failure to create cairo surface: out of memory
    Segmentation fault (core dumped)

**Comment by bhpayne** [comment]
After switching graphviz from

    overlap = false;

to

    overlap = prism;
    pack = true;

now I get

    Command '['neato', '-Tpng', '/home/appuser/app/static/graphviz.dot', '-oall_derivation.png']' timed out after 30 seconds

**Comment by bhpayne** [comment]
Avoided issues with neato by switching to d3js in 1564e3f35eec903d8986351104d3c6395d18c455
