### ISSUE TITLE
orientation of the graph in the web interface

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/proofofconcept#26]
intuitive flow is from top-to-bottom or left-to-right. Current graph is spring-force model with gravity for centering. 

To do: starting point should be at top or left, final expressions should be bottom or right.

**Comment by marekyggdrasil** [comment]
I think in general user experience and readability would improve a lot if we find a way to allow only 45*k degrees angles in the graph and vertices would be snapped to some invisible grid. It would look very eye candy.

Example of same graph, left one is snapped to grid and has restrained angles:

![fig2_5_3](https://user-images.githubusercontent.com/8202674/40145624-9ebe95c6-5930-11e8-8fd4-c9d3025e8a5f.png)

[https://courses.lumenlearning.com/math4libarts/chapter/graph-theory/](source)

**Comment by bhpayne** [comment]
this is related to #70

**Comment by bhpayne** [comment]
added a "linear index" float value to each step within a derivation; this could be leveraged for orientation in d3js

**Comment by bhpayne** [comment]
In graphviz, pin node that has the lowest "linear index" to the top of the graph. If necessary, pin the highest "linear index" to the bottom of the graph.

https://stackoverflow.com/questions/8309201/graphviz-fixed-node-positions

https://graphviz.gitlab.io/_pages/doc/info/attrs.html#d:pin

https://observablehq.com/@magjac/placing-graphviz-nodes-in-fixed-positions

**Comment by bhpayne** [comment]
Example derivations where this is relevant: 

 - Euler equation proof

**Comment by bhpayne** [comment]
In a large graph I added a single `pos` to one node

    1337934 [shape=invtrapezium, color=blue, label="",image="/home/appuser/app/static/declareinitialexpr.png",labelloc=b, pos="0,0!"];

and then ran

    neato -Tpng graphviz.dot -o newgraph.png

That didn't work, probably because `neato` wasn't looking for positions.  I also tried an explicit pin,

    1337934 [shape=invtrapezium, color=blue, label="",image="/home/appuser/app/static/declareinitialexpr.png",labelloc=b, pos="0,0!", pin=true];

but that didn't alter the layout. When I told neato to look for positions, I get an error because only one has `pos`

    neato -n -Tpng graphviz.dot -o newgraph.png
        Error: node 5427510 in graph physicsDerivation has no position as required by the -n flag

Then I added `pos="0,0"` to all the other nodes. The `neato -n` worked but the graph was unreadable (and the one static `0,0!` didn't seem to take effect).

**Comment by bhpayne** [comment]
I can get node positions to change if I use non-negative coordinate values, e.g., `pos="2,1!", pin=true`

I pinned the first and last inference rules but the layout was not improved

**Comment by bhpayne** [comment]
https://github.com/allofphysicsgraph/proofofconcept/tree/gh-pages/v7_pickle_web_interface/flask/from_freelancers/20200608_pinned_nodes_Evgeniy

3f5b75b1cf5bb0d00625b5c736e4e4c315d015dd
