### ISSUE TITLE
store expressions as parse tree

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/proofofconcept#31]
"Programming in Mathematica is based on transforming trees. The built-in function TreeFormallows us to visually represent the tree backbone of Mathematica programs and data structures"
source:
http://blog.wolfram.com/2007/05/13/symbolic-programming-visualized/

I'd like to see whether Mathematica's treeform is an Abstract Syntax Tree or Parse Tree
http://stackoverflow.com/questions/5967888/whats-the-difference-between-parse-trees-and-abstract-syntax-trees
An easy test is to test the output of
Treeform[(a+b)+c]
if the output doesn't include paranethesis, then treeform is an AST.

To make this useful, see
https://mathematica.stackexchange.com/questions/29565/getting-a-usable-expression-tree

**Comment by msgoff** [comment]
https://github.com/allofphysicsgraph/proofofconcept/blob/mike/v3_CSV/bin/mike/parsed_ast_output

I think using the ast's are the way to go and we can use memory locations as the temporary ids. 
It's clean, easy to generate, consistent with the goal of showing each step of the derivation.

**Comment by msgoff** [comment]
![antlr4_parse_tree_1](https://user-images.githubusercontent.com/10015644/33801001-eeb7e702-dd44-11e7-8e1b-4657ec78439f.png)

**Comment by msgoff** [comment]
The above output is from  Antlr4
I put in the expression 1 + x, and the parse tree was created automagically.

**Comment by msgoff** [comment]
Treeform[(a+b)+c] does not include the parenthesis in Mathematica.
![mathematica](https://user-images.githubusercontent.com/10015644/33801443-4fa5fdcc-dd29-11e7-924f-fa8535587a30.png)

**Comment by bhpayne** [comment]
Status update: I'll be limiting myself to just Latex input in order to make some progress

https://physicsderivationgraph.blogspot.com/2018/05/limiting-my-effort-to-just-latex-for.html

**Comment by msgoff** [comment]
Sounds good. I will look at mathml and ast.

**Comment by msgoff** [comment]
AST looses formatting information.

https://baron.readthedocs.io/en/latest/index.html 
Full Syntax Tree preserves all formatting information as well as the ast.

**Comment by msgoff** [comment]
https://github.com/AkiraHakuta/antlr4_tex2sym

**Comment by bhpayne** [comment]
Symmetry 2018, 10(7), 285; https://doi.org/10.3390/sym10070285 

A Step-by-Step Solution Methodology for Mathematical Expressions

https://www.mdpi.com/2073-8994/10/7/285/htm

**Comment by bhpayne** [comment]
"Extracting Mathematical Semantics from LATEX Documents"

https://pdfs.semanticscholar.org/a91a/f3fa64e1296de470206f375a29ddc1c7b54d.pdf

**Comment by bhpayne** [comment]
A LaTeX parser and utilities.

https://github.com/tamuratak/latex-utensils

**Comment by bhpayne** [comment]
http://mathlex.org/doc/how-mathlex-works

**Comment by bhpayne** [comment]
http://mirrors.ibiblio.org/CTAN/info/symbols/comprehensive/symbols-a4.pdf

**Comment by bhpayne** [comment]
https://docs.mathlive.io/module-mathlive.html#latexToAST

https://docs.mathlive.io/tutorial-MATHJSON.html

It's a Javascript library, but the source code is available
https://github.com/arnog/mathliveand development is active.

https://github.com/arnog/mathlive/blob/master/src/core/parser.js

https://github.com/arnog/mathlive/blob/master/src/core/lexer.js

**Comment by bhpayne** [comment]
"Towards semantic mathematical editing"

https://www.texmacs.org/joris/semedit/semedit.html

**Comment by bhpayne** [comment]
https://vmext.wmflabs.org/

**Comment by bhpayne** [comment]
https://github.com/dabeaz/ply
@msgoff is using this tool to try to parse latex.

**Comment by bhpayne** [comment]
Converting Latex to SymPy addresses this requirement. See https://docs.sympy.org/latest/tutorial/manipulation.html and https://docs.sympy.org/latest/modules/printing.html#sympy.printing.dot.dotprint

In latex_to_sympy see create_AST_png_for_latex()

    symp_lat = parse_latex(expr_latex)
    graphviz_of_AST_for_expr = sympy.printing.dot.dotprint(symp_lat)
