### ISSUE TITLE
shebang line from Mac doesn't work on Linux

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/proofofconcept#36]
Currently all Python scripts start with a shebang line for Mac
`#!/opt/local/bin/python`
This doesn't work on Ubuntu

The motivation for using the shebang is to enable
`./bin/<scriptname>.py`

Without the shebang, need to call
`python bin/<scriptname>.py`

**Comment by bhpayne** [comment]
```
cd bin
for filename in `ls *.py`; do sed -i '/^#!\/opt\/local/d' $filename; done
```

**Comment by msgoff** [comment]
#!/usr/bin/env python
should make the scripts portable. 
http://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my

**Comment by bhpayne** [comment]
No longer relevant since I'm running from within a Docker image
