### ISSUE TITLE
web frontend: enter a LaTeX expression, get a picture

### ISSUE THREAD

**Issue by bhpayne** [allofphysicsgraph/proofofconcept#54]

**Comment by msgoff** [comment]
![latex_d3_mathjax](https://user-images.githubusercontent.com/10015644/43039615-d57fec52-8cfe-11e8-9cf2-7266cf7520e7.png)

**Comment by msgoff** [comment]
d3.js and mathjax would make it pretty easy to enter latex and render to html and generate an svg.

**Comment by bhpayne** [comment]
https://github.com/jgm/texmath/

https://johnmacfarlane.net/texmath.html
